services:

  db:
    restart: always
    image: kauahensilva/orientdb:2.2.37
    ports:
      - "2424:2424"
      - "2480:2480"
    volumes:
      - /orentdb/config:/opt/orientdb/config
      - /orientdb/databases:/opt/orientdb/databases
      - /orientdb/backup:/opt/orientdb/backupi
    environment:
      ORIENTDB_ROOT_PASSWORD: 'root'
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        preferences:
          - spread: node.hostname
          
  # server:
  #   build:
  #     context: ./src  

  #   environment:
  #     - HOST=orientdb
  #     - PASSWORDBD=root
  #     - HOSTBD=root

  #   # Limita a quantidade de mem√≥ria que o container pode utilizar
  #   mem_limit: 2g